### ISSUE TITLE
How to update labels in jME from outside of SimpleApplication.

### ISSUE THREAD

**Issue by erikmartinessanches** [jMonkeyEngine-Contributions/Lemur#110]
I've followed the [Lemur Getting started](https://github.com/jMonkeyEngine-Contributions/Lemur/wiki/Getting-Started#make-a-gui) example and now have a situation similar to the "full source example" at the bottom of the page in the above link. 

In jME's simpleInitApp() I create the GUI:

```
        GuiGlobals.initialize(this);
        BaseStyles.loadGlassStyle();
        GuiGlobals.getInstance().getStyles().setDefaultStyle("glass");
        Container myUiElements = new Container();
        myUiElements.setName("myUiElements");
        guiNode.attachChild(myUiElements);
        myUiElements.setLocalTranslation(0, 480, 0);
        Label myLabel = new Label("Initial label text");
        myLabel.setName("myLabel");
        myUiElements.addChild(myLabel);
```

Then, from my own networking code, which is outside of the class that extends jME's SimpleApplication, I would like to modify the label's text. 

I tried

```
        final Node tempNode = (Node) clientWindow.getGuiNode().getChild("myUiElements");
        final Label tempLabel = tempNode.getChild("myLabel"); //This does not give me access to Label's .setText() method.
```

And, do I also have to "[enqueue](https://wiki.jmonkeyengine.org/docs/3.4/core/app/multithreading.html)" it?

**Comment by pspeed42** [comment]
Answered on the JME forum.
