### ISSUE TITLE
Lemur available as maven dependency

### ISSUE THREAD

**Issue by zielezin** [jMonkeyEngine-Contributions/Lemur#29]
Hi,

Is Lemur published in any maven repo?
This should be pretty easy with gradle.
Maybe this repo could be used: http://updates.jmonkeyengine.org/maven/

**Comment by pspeed42** [comment]
Soon... and it will be in a proper repo like jcenter.  Zay-Es and
Zay-ES-Net are already there... I'm working through my library stack from
bottom to top.

**Comment by pspeed42** [comment]
Lemur related jars are now up on jcenter... gradle style dependencies are:
com.simsilica:lemur:1.6.1
com.simsilica:lemur-proto:1.5.1
com.simsilica:lemur-props:1.0.1

Main Lemur page in bintray:
https://bintray.com/simsilica/Sim-tools/lemur/view

**Comment by zielezin** [comment]
Just hooked Lemur as dependency and it worked fine including source download.
Thank you.

**Comment by pspeed42** [comment]
Glad to hear external confirmation that it worked!  :)
