### ISSUE TITLE
Groovy Math Extension: Typo in method name

### ISSUE THREAD

**Issue by MeFisto94** [jMonkeyEngine-Contributions/Lemur#33]
As the title says just a little typo in ScriptMonkey's Code.

In https://github.com/jMonkeyEngine-Contributions/Lemur/blob/master/extensions/ScriptMonkey/src/com/simsilica/script/MathApi.groovy#L106 there is: `Vector2f vec3( ...)` where it should be `Vector2f vec2(...)`

**Comment by pspeed42** [comment]
Thanks for the find.  If you happen to have it checked out and feel time-generous then maybe you can submit a PR?

**Comment by MeFisto94** [comment]
I didn't have it checked out but I just did :)

**Comment by pspeed42** [comment]
Thanks.  PR approved and applied.
