### ISSUE TITLE
Elements don't clear focus after being removed from the screen

### ISSUE THREAD

**Issue by MoffKalast** [jMonkeyEngine-Contributions/Lemur#42]
A focused Button can be activated using the space bar after the container has been removed from the main lemur root node.

Notes:
- my setup uses the separate viewport method instead of rendering inside the guiNode
- the button is attached to a Container
- Container layout is set to SpringGrid with multiple rows of buttons

**Comment by pspeed42** [comment]
Just a note for myself... this is related to: https://github.com/jMonkeyEngine-Contributions/Lemur/issues/28

**Comment by pspeed42** [comment]
This should be fixed now and will show up in v 1.10
