### ISSUE TITLE
Issue with new mouse wheel scrolling support on ListBox

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine-Contributions/Lemur#49]
I am running to an issue when using this new feature.
If do not use mouse wheel scrolling, then list rolls correctly by dragging with mouse click but if try scrolling then dragging with mouse is not working correctly. See below video: 

https://youtu.be/mGGn_m4N2BA

**Comment by pspeed42** [comment]
This should be fixed in head.  The demo works properly for me now.  It will be in 1.10 when I release it.
