### ISSUE TITLE
Feature request : Support smoothly increasing/decreasing slider value when pressing and holding slider +/- button

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine-Contributions/Lemur#63]
... while making the speed to be modifiable.

**Comment by pspeed42** [comment]
Yes, but if was done in a way that could be added as styling on the buttons then it doesn't need to be hard-coded into Slider itself.  Then users could use whatever method they wanted.  hold that slowly increases, hold that increases faster if you move the mouse up/down.  Hold that rolls through increments as you move the mouse providing finer grained changes than dragging the slider, etc..

I can pretty much guarantee that if I include code for this in lemur that it won't be hard coded into Slider.

**Comment by Ali-RS** [comment]
I see, I haven't dealt with lemur styling so didn't know it could be done that way.

**Comment by pspeed42** [comment]
I've implemented the basics of this in the built in glass style.  The groovy code was simple enough and I wasn't sure where I wanted to put a Java class that did this.  The only magic was the new Hover ButtonAction which makes it easy to get per-frame events while the mouse is over a button.

I'm going to close this issue.  If you have ideas on how this could/should be extended then feel free to reopen or create a new issue.  Else I feel like the spirit of the request has been implemented.

**Comment by Ali-RS** [comment]
Thanks
