### ISSUE TITLE
changing border of container will change the background too...

### ISSUE THREAD

**Issue by RayanFar** [jMonkeyEngine-Contributions/Lemur#76]
changing border of container will change the background too...

             new Container().setBorder(new QuadBackgroundComponent(ColorRGBA.Blue));

version -> lemur 1.12.0

**Comment by pspeed42** [comment]
I'm not sure what this means.  "Border" is just a layer.  You can have a border that is also a quad, for example, and will fill in the whole "background"... but then you can also have a background component that will be drawn on top of that.

Is that not working or is there just a misunderstanding?

**Comment by RayanFar** [comment]
no it is not working...

        win.setBorder(new QuadBackgroundComponent(ColorRGBA.Blue));
        win.setBackground(new QuadBackgroundComponent(ColorRGBA.Black));

**Comment by pspeed42** [comment]
The default margin for QuadBackgroundComponent is 0,0 so those will lay right on top of each other.
Try:
    win.setBorder(new QuadBackgroundComponent(ColorRGBA.Blue, 5, 5));
    win.setBackground(new QuadBackgroundComponent(ColorRGBA.Black, 5, 5));
...or similar non-zero margin values.
