### ISSUE TITLE
Feature Request: Add support for float numbers in numeric TextFilter of DocumentModelFilter

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine-Contributions/Lemur#82]

**Comment by pspeed42** [comment]
Can you describe what you mean by this?  Is it a limitation of the filtered document model or just the lack of an implementation?

...ie: is it possible for a user to implement their own or not?

**Comment by Ali-RS** [comment]
Sorry, I forgot to close this.

>...ie: is it possible for a user to implement their own or not?
Yes, I was able to implement my own filter for this.


```
DocumentModelFilter doc = new DocumentModelFilter();
doc.setInputTransform(TextFilters.charFilter(Predicates.or(TextFilters.isDigit(), TextFilters.isInChars('.'))));
```

I am closing this.
