### ISSUE TITLE
why you dont support  percentage layout?

### ISSUE THREAD

**Issue by qq1053831109** [jMonkeyEngine-Contributions/Lemur#88]
why you dont support  percentage layout?

**Comment by pspeed42** [comment]
It does.

**Comment by qq1053831109** [comment]
so why?

**Comment by pspeed42** [comment]
Because.

**Comment by pspeed42** [comment]
Note: you will find you will get better answers if you ask real questions.

**Comment by pspeed42** [comment]
Questions should be asked on the Lemur section of the JME forums.  This is for reporting bugs or making feature requests.
